name: formx
description: Build, validate and fill forms easily with Formx.
version: 0.9.2
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0" 

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
