name: formx
description: Access, build, validate, sanitize and fill forms easily with Formx.
version: 0.17.1
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension 
 - validator
 - sanitizer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: '>=2.9.0 <3.0.0'
  meta: '>=1.10.0 <2.0.0'
  recase: '>=4.1.0 <5.0.0'
  string_validator: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
