name: formx
description: Access, build, validate, sanitize and fill forms easily with Form/Field extensions.
version: 0.22.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension 
 - validator
 - sanitizer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cross_file: ^0.3.4+2
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.13.0
  meta: '>=1.15.0 < 2.0.0'
  recase: '>=4.1.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true