name: formx
description: Access, build, validate, sanitize and fill forms easily with Formx.
version: 0.12.2
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.10.0 <2.0.0'
  recase: ^4.1.0
  string_validator: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
