name: formx
description: Access, build, validate, sanitize and fill forms easily with Form/Field extensions.
version: 0.21.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension 
 - validator
 - sanitizer

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cross_file: ^0.3.4+2
  flutter:
    sdk: flutter
  mask_text_input_formatter: '>=2.9.0 <3.0.0' # replace with branvier's
  meta: '>=1.15.0 < 2.0.0'
  recase: '>=4.1.0 <5.0.0'
  string_validator: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true