name: formx
description: Access, build, format, validate, sanitize and fill forms easily with Form/Field extensions.
version: 0.36.2
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension 
 - validator
 - formatter
 - sanitizer

environment:
  flutter: '>=3.19.0'
  sdk: ^3.3.0

dependencies:
  collection: ^1.18.0
  cross_file: ^0.3.4+1
  flutter:
    sdk: flutter
  meta: ^1.15.0
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true