name: formx
description: Access, build, format, validate, sanitize and fill forms easily with Form/Field extensions.
version: 0.29.2
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/formx
topics:
 - form
 - extension 
 - validator
 - formatter
 - sanitizer

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  collection: '>=1.18.0 <2.0.0'
  cross_file: ^0.3.4+1
  flutter:
    sdk: flutter
  meta: '>=1.15.0 < 2.0.0'
  recase: '>=4.1.0 <5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true